version: '3.8'

services:
  statping-test:
    image: status:latest
    container_name: statping-test
    restart: always
    ports:
      - "3503:8080"
    environment:
      DB_CONN: postgres
      DB_HOST: 10.147.18.245
      DB_PORT: 54002
      DB_USER: statping
      DB_PASS: statping
      DB_DATABASE: statping-elcoheteboom
